### ISSUE TITLE
Support building for multiple architectures

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/ironic-image#502]
User Story

As a developer/user/operator I would like to use pre-built ironic images on multiple architectures because it is convenient (compared to building everything yourself).

Detailed Description
We currently only publish amd64 container images, but there are other popular architectures.
I suggest we look at how CAPI/CAPM3 has structured the Makefile with a docker-build-all target for building all supported architectures. It will probably be a bit different for Ironic though, since it is not written in Go.

Once we can build these images, it should be fairly trivial to also make CI build and publish them together with a multi-arch manifest for easy consumption.

/kind feature

**Comment by dtantsur** [comment]
This is going to be a huge can of worms :) Start with https://github.com/metal3-io/ironic-image/pull/437 if you feel courageous.

**Comment by Rozzii** [comment]
/tirage accepted
After we have sorted out our CI "restructuring" we could ask for some Oracle arm compute power from CNCF to have some ARM CI.
/help

**Comment by diconico07** [comment]
To act as some kind of todo list for that, here are what I believe to be the needed elements to have a fully working multi-architecture support:
- [ ] IPA downloader grabs architecture specific images (handled in metal3-io/ironic-ipa-downloader#69)
- [ ] Ironic image entrypoint detects architecture specific images and fills the `_by_arch` Ironic config fields (handled in #713)
- [ ] Ironic image has EFI image for multiple architecture (also in #713)
- [ ] For correct (i)PXE support, per arch iPXE binaries and config are needed (no PR for now)

For now I focused entirely on refish virtual media support, so I didn't yet took a look at iPXE situation in Ironic configuration files

**Comment by Rozzii** [comment]
> To act as some kind of todo list for that, here are what I believe to be the needed elements to have a fully working multi-architecture support:
> 
>     * [ ]  IPA downloader grabs architecture specific images (handled in [Add architecture specific suffixes to symlinks ironic-ipa-downloader#69](https://github.com/metal3-io/ironic-ipa-downloader/pull/69))[ ]  Ironic image entrypoint detects architecture specific images and fills the `_by_arch` Ironic config fields (handled in [✨ Multi architecture support for IPA kernel/ramdisk and EFI bootloader #713](https://github.com/metal3-io/ironic-image/pull/713))[ ]  Ironic image has EFI image for multiple architecture (also in [✨ Multi architecture support for IPA kernel/ramdisk and EFI bootloader #713](https://github.com/metal3-io/ironic-image/pull/713))[ ]  For correct (i)PXE support, per arch iPXE binaries and config are needed (no PR for now)
> 
> 
> For now I focused entirely on refish virtual media support, so I didn't yet took a look at iPXE situation in Ironic configuration files

So if I understand correctly only the  "For correct (i)PXE support, per arch iPXE binaries and config are needed" is missing, is there any action we could do to fix this?

**Comment by Rozzii** [comment]
Is there anything else we have to do for this issue @diconico07 @synthe102
